import {wireBeing} from './mesh.js';
// Visual-only geometry. No positions are uploaded to physics textures.
export class InertStructure{
 constructor(gpu){this.gpu=gpu;this.active=false;this.geometry=null;}
 build(){if(this.geometry)return;const g=this.gpu.gl,m=wireBeing(2048,12345,true);this.geometry=m;this.program=this.gpu.program(`#version 300 es
precision highp float;layout(location=0)in vec3 position;uniform vec3 right,up,back,eye;uniform float aspect,zoomScale;
void main(){vec3 d=position-eye;float z=-dot(d,back),near=.0005,far=10000.;gl_Position=vec4(dot(d,right)*1.8*zoomScale/aspect,dot(d,up)*1.8*zoomScale,(far+near)/(far-near)*z-2.*far*near/(far-near),z);}`,`#version 300 es
precision highp float;out vec4 result;void main(){result=vec4(.78,.88,1.,1.);}`);
 const buffer=pairs=>{const data=new Float32Array(pairs.flatMap(ids=>ids.flatMap(i=>m.vertices[i]))),b=g.createBuffer();g.bindBuffer(g.ARRAY_BUFFER,b);g.bufferData(g.ARRAY_BUFFER,data,g.STATIC_DRAW);return {buffer:b,count:data.length/3};};this.lines=buffer(m.edges);this.surface=buffer(m.faces);this.vao=g.createVertexArray();
 const top=Math.max(...m.vertices.map(v=>v[1]));this.eyeNodes=[];for(const sign of [-1,1]){let best=Infinity,id=-1;m.vertices.forEach(([x,y,z],i)=>{if(sign*x<=0||y<top-.55||z<.05)return;const e=(x-sign*.13)**2+(y-(top-.30))**2+(z-.25)**2;if(e<best){best=e;id=i;}});this.eyeNodes.push(id);}
 const data=[];this.nodeStyles=[];
 m.vertices.forEach((v,i)=>{const h=(Math.imul(i+1,1664525)+1013904223)>>>0,size=.8+(h%1024)/1023*1.6,eye=this.eyeNodes.includes(i),style=eye?[.015,.24,1,9]:[1,1,1,size];this.nodeStyles.push(style);data.push(...v,...style);});this.nodes=g.createBuffer();g.bindBuffer(g.ARRAY_BUFFER,this.nodes);g.bufferData(g.ARRAY_BUFFER,new Float32Array(data),g.STATIC_DRAW);
 this.pointProgram=this.gpu.program(`#version 300 es
precision highp float;layout(location=0)in vec3 position;layout(location=1)in vec4 style;out vec3 color;uniform vec3 right,up,back,eye,bodyColor;uniform float aspect,zoomScale,blobSize,pixelRatio,maxPointSize;
void main(){vec3 d=position-eye;float z=-dot(d,back),near=.0005,far=10000.;gl_Position=vec4(dot(d,right)*1.8*zoomScale/aspect,dot(d,up)*1.8*zoomScale,(far+near)/(far-near)*z-2.*far*near/(far-near),z);gl_PointSize=clamp(style.w*blobSize*pixelRatio*sqrt(8./max(z,.1))*sqrt(zoomScale),1.,maxPointSize);color=style.w>8.?style.rgb:bodyColor;}`,`#version 300 es
precision highp float;in vec3 color;out vec4 result;void main(){float r=length(gl_PointCoord-.5)*2.;if(r>1.)discard;result=vec4(color,1.-smoothstep(.72,1.,r));}`);
 }
 draw(camera){if(!this.active)return;this.build();const g=this.gpu.gl,p=this.program;g.bindFramebuffer(g.FRAMEBUFFER,null);g.viewport(0,0,this.gpu.canvas.width,this.gpu.canvas.height);g.bindVertexArray(this.vao);g.disableVertexAttribArray(1);g.useProgram(p);for(const [name,off]of [['right',0],['up',3],['back',6],['eye',9]])g.uniform3fv(g.getUniformLocation(p,name),camera.subarray(off,off+3));g.uniform1f(g.getUniformLocation(p,'aspect'),this.gpu.canvas.width/this.gpu.canvas.height);g.uniform1f(g.getUniformLocation(p,'zoomScale'),this.gpu.zoomScale);g.disable(g.BLEND);g.enable(g.DEPTH_TEST);g.depthFunc(g.LEQUAL);g.depthMask(true);g.clear(g.DEPTH_BUFFER_BIT);g.enableVertexAttribArray(0);const bind=b=>{g.bindBuffer(g.ARRAY_BUFFER,b.buffer);g.vertexAttribPointer(0,3,g.FLOAT,false,0,0);};bind(this.surface);g.colorMask(false,false,false,false);g.enable(g.POLYGON_OFFSET_FILL);g.polygonOffset(1,1);g.drawArrays(g.TRIANGLES,0,this.surface.count);g.disable(g.POLYGON_OFFSET_FILL);g.colorMask(true,true,true,true);g.depthMask(false);bind(this.lines);g.drawArrays(g.LINES,0,this.lines.count);g.useProgram(this.pointProgram);g.uniform3fv(g.getUniformLocation(this.pointProgram,'bodyColor'),this.gpu.eigenColor);for(const [name,off]of [['right',0],['up',3],['back',6],['eye',9]])g.uniform3fv(g.getUniformLocation(this.pointProgram,name),camera.subarray(off,off+3));for(const [name,value]of [['aspect',this.gpu.canvas.width/this.gpu.canvas.height],['zoomScale',this.gpu.zoomScale],['blobSize',this.gpu.eigenSize],['pixelRatio',Math.min(devicePixelRatio||1,2)],['maxPointSize',this.gpu.maxPointSize]])g.uniform1f(g.getUniformLocation(this.pointProgram,name),value);g.bindBuffer(g.ARRAY_BUFFER,this.nodes);g.vertexAttribPointer(0,3,g.FLOAT,false,28,0);g.enableVertexAttribArray(1);g.vertexAttribPointer(1,4,g.FLOAT,false,28,12);g.enable(g.BLEND);g.blendFunc(g.SRC_ALPHA,g.ONE_MINUS_SRC_ALPHA);g.drawArrays(g.POINTS,0,this.geometry.vertices.length);g.disable(g.BLEND);g.depthMask(true);g.disable(g.DEPTH_TEST);g.bindVertexArray(this.gpu.vao);}
}
