import {buildMesh} from './mesh.js';
const unit=p=>{const r=Math.hypot(...p);return p.map(v=>v/r);},cross=(a,b)=>[a[1]*b[2]-a[2]*b[1],a[2]*b[0]-a[0]*b[2],a[0]*b[1]-a[1]*b[0]],sub=(a,b)=>a.map((v,k)=>v-b[k]),dot=(a,b)=>a.reduce((s,v,k)=>s+v*b[k],0);
const pink=unit([.85,.5,.3]),amber=unit([.65,-.7,.35]),horn=unit([-.5,.85,-.2]);
function shape(u){const bump=(d,w)=>Math.exp((dot(u,d)-1)/w),p=bump(pink,.105),a=bump(amber,.075),h=bump(horn,.075),r=1.12+.85*p+.90*a+1.9*h;return [u[0]*r+1.15*h*h*h,u[1]*r+.30*h*h,u[2]*r+.26*p-.24*a+.16*h*h];}
function color(u){const scores=[dot(u,pink),dot(u,amber),dot(u,horn)],m=Math.max(...scores);return m<.77?[.08,.25,1]:scores[2]===m?[.02,.88,1]:scores[0]===m?[1,.04,.65]:[1,.63,.015];}
export function makeLobeform(capacity=2048){const t=(1+Math.sqrt(5))/2,vertices=[[-1,t,0],[1,t,0],[-1,-t,0],[1,-t,0],[0,-1,t],[0,1,t],[0,-1,-t],[0,1,-t],[t,0,-1],[t,0,1],[-t,0,-1],[-t,0,1]].map(unit);let faces=[[0,11,5],[0,5,1],[0,1,7],[0,7,10],[0,10,11],[1,5,9],[5,11,4],[11,10,2],[10,7,6],[7,1,8],[3,9,4],[3,4,2],[3,2,6],[3,6,8],[3,8,9],[4,9,5],[2,4,11],[6,2,10],[8,6,7],[9,8,1]];
 for(let level=0;level<2;level++){const cache=new Map(),mid=(a,b)=>{const key=[a,b].sort((a,b)=>a-b).join();if(!cache.has(key)){cache.set(key,vertices.length);vertices.push(unit(vertices[a].map((v,k)=>(v+vertices[b][k])/2)));}return cache.get(key);};faces=faces.flatMap(([a,b,c])=>{const ab=mid(a,b),bc=mid(b,c),ca=mid(c,a);return [[a,ab,ca],[b,bc,ab],[c,ca,bc],[ab,bc,ca]];});}
 const points=vertices.map(shape),center=[0,1,2].map(k=>points.reduce((s,p)=>s+p[k],0)/points.length);for(const p of points)for(let k=0;k<3;k++)p[k]-=center[k];const mesh=buildMesh(points,faces,capacity);mesh.stiffnessScale=32;mesh.pointScale=.25;mesh.bodyStyle=new Float32Array(capacity*4);for(let i=0;i<mesh.count;i++){mesh.v.set([.08*points[i][2],-.035*points[i][2],.035*points[i][1]-.08*points[i][0],1],i*4);mesh.bodyStyle.set([...color(vertices[i]),.4],i*4);}
 const triangles=[],lines=[],bindings=new Map();for(const ids of faces){const [a,b,c]=ids.map(i=>points[i]),e0=unit(sub(b,a)),normal=unit(cross(sub(b,a),sub(c,a))),e1=cross(normal,e0);const record=w=>{const u=unit([0,1,2].map(k=>ids.reduce((s,id,i)=>s+vertices[id][k]*w[i],0))),key=u.map(x=>Math.round(x*1e8)).join(','),target=shape(u).map((v,k)=>v-center[k]),base=[0,1,2].map(k=>ids.reduce((s,id,i)=>s+points[id][k]*w[i],0)),offset=sub(target,base);if(!bindings.has(key))bindings.set(key,[...ids,...w,dot(offset,e0),dot(offset,e1),dot(offset,normal),...color(u)]);return bindings.get(key);};let tiles=[[[1,0,0],[0,1,0],[0,0,1]]];for(let j=0;j<2;j++)tiles=tiles.flatMap(([a,b,c])=>{const mid=(x,y)=>x.map((v,k)=>(v+y[k])/2),ab=mid(a,b),bc=mid(b,c),ca=mid(c,a);return [[a,ab,ca],[b,bc,ab],[c,ca,bc],[ab,bc,ca]];});for(const tile of tiles){const r=tile.map(record);triangles.push(...r.flat());lines.push(...r[0],...r[1],...r[1],...r[2],...r[2],...r[0]);}}
 mesh.skin={triangles:new Float32Array(triangles),lines:new Float32Array(lines),faces:triangles.length/36,vertices:bindings.size};return mesh;
}
export class LobeformSkin{
 constructor(gpu){this.gpu=gpu;this.active=false;this.mesh=null;}
 set(mesh){this.mesh=mesh;if(this.program)return;const g=this.gpu.gl;this.program=this.gpu.program(`#version 300 es
precision highp float;layout(location=0)in vec3 ids;layout(location=1)in vec3 weights;layout(location=2)in vec3 offset;layout(location=3)in vec3 tint;uniform sampler2D positions;uniform vec3 right,up,back,eye;uniform float aspect,zoomScale;out vec3 color;
vec3 pos(float id){int i=int(id);return texelFetch(positions,ivec2(i%64,i/64),0).xyz;}
void main(){vec3 a=pos(ids.x),b=pos(ids.y),c=pos(ids.z),u=normalize(b-a),n=normalize(cross(b-a,c-a)),v=cross(n,u),p=a*weights.x+b*weights.y+c*weights.z+u*offset.x+v*offset.y+n*offset.z,d=p-eye;float z=-dot(d,back),near=.0005,far=10000.;gl_Position=vec4(dot(d,right)*1.8*zoomScale/aspect,dot(d,up)*1.8*zoomScale,(far+near)/(far-near)*z-2.*far*near/(far-near),z);color=tint;}`,`#version 300 es
precision highp float;in vec3 color;out vec4 result;void main(){result=vec4(color,1);}`);this.vao=g.createVertexArray();const buffer=data=>{const b=g.createBuffer();g.bindBuffer(g.ARRAY_BUFFER,b);g.bufferData(g.ARRAY_BUFFER,data,g.STATIC_DRAW);return {buffer:b,count:data.length/12};};this.lines=buffer(mesh.skin.lines);this.faces=buffer(mesh.skin.triangles);}
 draw(camera){if(!this.active)return;const g=this.gpu.gl,p=this.program;g.bindFramebuffer(g.FRAMEBUFFER,null);g.viewport(0,0,this.gpu.canvas.width,this.gpu.canvas.height);g.useProgram(p);g.bindVertexArray(this.vao);this.gpu.bind(p,'positions',this.gpu.states[this.gpu.current].p,0);for(const [name,k]of [['right',0],['up',3],['back',6],['eye',9]])g.uniform3fv(g.getUniformLocation(p,name),camera.subarray(k,k+3));g.uniform1f(g.getUniformLocation(p,'aspect'),this.gpu.canvas.width/this.gpu.canvas.height);g.uniform1f(g.getUniformLocation(p,'zoomScale'),this.gpu.zoomScale);g.disable(g.BLEND);g.enable(g.DEPTH_TEST);g.depthFunc(g.LEQUAL);g.depthMask(true);g.clear(g.DEPTH_BUFFER_BIT);const bind=b=>{g.bindBuffer(g.ARRAY_BUFFER,b.buffer);for(let i=0;i<4;i++){g.enableVertexAttribArray(i);g.vertexAttribPointer(i,3,g.FLOAT,false,48,i*12);}};bind(this.faces);g.colorMask(false,false,false,false);g.enable(g.POLYGON_OFFSET_FILL);g.polygonOffset(1,1);g.drawArrays(g.TRIANGLES,0,this.faces.count);g.disable(g.POLYGON_OFFSET_FILL);g.colorMask(true,true,true,true);g.depthMask(false);bind(this.lines);g.drawArrays(g.LINES,0,this.lines.count);g.depthMask(true);g.disable(g.DEPTH_TEST);g.bindVertexArray(this.gpu.vao);}
}
